### ISSUE TITLE
Primevalist Celebrant can have "fearless" ability

### ISSUE THREAD

**Issue by sevu** [doofus-01/wesnoth-Archaic_Era#2]
This is currently being discussed in Ageless:
https://github.com/ProditorMagnus/Ageless-for-1-11/issues/21

**Comment by doofus-01** [comment]
Thanks for bringing this to my attention, I will have to look into this.

**Comment by doofus-01** [comment]
I think this is fixed, will be in the next upload.  The plague issue turned out not to matter, I'd forgotten that all traits are covered - the mainline ones are actually variants.

**Comment by ProditorMagnus** [comment]
Link 586b18a00b27dccd98ce0f5e36b71b7364b7aee1
